ALTER TABLE system_settings
  ADD COLUMN IF NOT EXISTS backup_daily_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS backup_weekly_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS backup_retention_count INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS backup_daily_hour INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS backup_weekly_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS backup_last_daily_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS backup_last_weekly_at TIMESTAMPTZ;

ALTER TABLE vps_backup_runs
  ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'manual';
